export enum UiActionType {
  // TOGGLE_SPLASH_SCREEN = 'TOGGLE_SPLASH_SCREEN',
  // TOGGLE_SHOP_INFO = 'TOGGLE_SHOP_INFO',
  // TOGGLE_SETTINGS = 'TOGGLE_SETTINGS',
  // TOGGLE_MENU = 'TOGGLE_MENU',
  // TOGGLE_TUTORIAL = 'TOGGLE_TUTORIAL',
  // SET_TUTORIAL_PAGE = 'SET_TUTORIAL_PAGE',

  SHOW_PRODUCT_INFO = 'SHOW_PRODUCT_INFO',
  SHOW_SCREENSHOT_SHADOW = 'SHOW_SCREENSHOT_SHADOW',
  SHOW_SPLASH_SCREEN = 'SHOW_SPLASH_SCREEN',
  SHOW_SHOP_INFO = 'SHOW_SHOP_INFO',
  SHOW_SETTINGS = 'SHOW_SETTINGS',
  SHOW_MENU = 'SHOW_MENU',
  SHOW_TUTORIAL = 'SHOW_TUTORIAL',

  HIDE_PRODUCT_INFO = 'HIDE_PRODUCT_INFO',
  HIDE_SCREENSHOT_SHADOW = 'HIDE_SCREENSHOT_SHADOW',
  HIDE_SPLASH_SCREEN = 'HIDE_SPLASH_SCREEN',
  HIDE_SHOP_INFO = 'HIDE_SHOP_INFO',
  HIDE_SETTINGS = 'HIDE_SETTINGS',
  HIDE_MENU = 'HIDE_MENU',
  HIDE_TUTORIAL = 'HIDE_TUTORIAL',

  HIDE_ALL = 'HIDE_ALL'
}

export enum DrinkingActionType {
  INIT_DRINKING = 'INIT_DRINKING',
  DRINK_ONE = 'DRINK_ONE',
  UNSIP_ONE = 'UNSIP_ONE',
  CHANGE_DRINK_AMOUNT = 'CHANGE_DRINK_AMOUNT'
}

export enum TimeActionType {
  TIME_AFTER_START = 'TIME_AFTER_START'
}

export enum NativeActionType {
  OPEN_WEBSITE = 'OPEN_WEBSITE',
  SHARE_APP = 'SHARE_APP',
  SHARE_SCREENSHOT = 'SHARE_SCREENSHOT'
}

export enum NotificationsActionType {
  INIT_NOTIFICATIONS_STATE = 'INIT_NOTIFICATIONS_STATE',
  UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS',
  UPDATE_START_END_NOTIFICATIONS = 'UPDATE_START_END_NOTIFICATIONS'
}

export enum PickerActionType {
  SHOW_PICKER = 'SHOW_PICKER',
  HIDE_PICKER = 'HIDE_PICKER'
}

export enum SettingsActionType {
  CHANGE_SETTINGS = 'CHANGE_SETTINGS',
  INIT_SETTINGS = 'INIT_SETTINGS',
  TOGGLE_LANGUAGE = 'TOGGLE_LANGUAGE',
  TOGGLE_TUTORIAL = 'TOGGLE_TUTORIAL',
  CHANGE_TEMP_SETTINGS = 'CHANGE_TEMP_SETTINGS',
  SAVE_PICKER = 'SAVE_PICKER',
  CANCEL_TEMP = 'CANCEL_TEMP'
}
